openapi: 3.0.2
info:
  title: OperDiensten
  description: Diensten voor een rooster
  version: '1.0'
       
paths:
  /Diensten/CreateTable:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat" 

  /Diensten/CreateViews:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /Diensten/GetObject:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal een enkele dienst op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het dienst record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_diensten'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"    
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"      

  /Diensten/GetObjects:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal een lijst met diensten op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het diensten record
          required: false
          schema:
            type: integer
            format: int32
            example: 10400    
        - in: query
          name: VERWIJDERD
          description: Toon welke records verwijderd zijn. Default = false
          required: false
          schema:
            type: boolean              
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: HASH
          description: HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is.
          required: false
          schema:
            type: string                
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = DATUM
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string    
        - in: query
          name: LID_ID
          description: Diensten van een bepaald lid
          required: false
          schema:
            type: string   
        - in: query        
          name: DATUM
          description: Zoek op datum
          required: false
          schema:
            type: string
            format: date    
        - in: query
          name: BEGIN_DATUM
          description: Begin datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date   
        - in: query
          name: EIND_DATUM
          description: Eind datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date                                                           
        - in: query
          name: TYPES
          description: Zoek op een of meerder type diensten. Types als CSV formaat
          required: false
          schema:
            type: string                                                
        - in: query
          name: AANWEZIG
          description: Haal alle diensten op waar lid aanwezig was
          required: false
          schema:
            type: boolean   
        - in: query
          name: AFWEZIG
          description: Haal alle diensten op waar lid NIET aanwezig was
          required: false
          schema:
            type: boolean


      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_diensten'
        304:
          description: "Data niet gemodificeerd, HASH in aanroep == hash in dataset"                     
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"         

  /Diensten/TotaalDiensten:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Leden en daarbij specificatie van diensten (totaal per jaar en totalen per maand)
      parameters:
        - in: query
          name: JAAR
          description: Voor welk jaar wordt de data opgevraagd
          required: true
          schema:
            type: integer
            format: int32
        - in: query
          name: LID_ID
          description: Voor welk lid wordt de data opgevraagd
          required: true
          schema:
            type: integer
            format: int32            
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/diensten_totaal'
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"    
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"     

  /Diensten/DeleteObject:
    delete:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het diensten record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string
        - in: query
          name: VERIFICATIE
          description: Controleer of record bestaat voordat het verwijderd wordt. Default = true
          required: false
          schema:
            type: boolean            
      responses:
        204:
          description: "Dienst verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"   
        404:
          description: "Data niet gevonden"             
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"        
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Diensten/RestoreObject:
    patch:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Record dat verwijderd is terug halen. VERWIJDERD marker krijgt reset
      parameters:
        - in: query
          name: ID
          description: Database ID van het record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string           
      responses:
        202:
          description: "Record(s) hersteld" 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Diensten/SaveObject:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Voeg nieuw dienst toe
      requestBody:
        description: Dienst data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_diensten_in'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_diensten'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                    
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, dienst is al ingevuld"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                   
    put:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Update bestaande dienst
      requestBody:
        description: Dienst data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_diensten_in'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_diensten'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"                    
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, dienst is al ingevuld"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT         

  schemas:
    oper_diensten_in:
      type: object
      properties:
        ID:
          description: Database ID van het dienten record
          type: integer
          format: int32
          example: 12871
        DATUM:
          description: Datum van de rooster 
          type: string
          format: date
          example: "2017-07-21"
        LID_ID: 
          description: Voor wie is deze dienst. Verwijzing naar leden tabel
          type: integer
          example: 10412       
        TYPE_DIENST_ID:
          description: Link naar type tabel. Geeft aan wat voor type dienst 
          type: integer
          format: int32   
          example: 12    
        AANWEZIG:
          description: Is lid aanwezig geweest
          type: boolean
          example: 1
        AFWEZIG:
          description: Lid is niet komen opdagen
          type: boolean
          example: 0
        UITBETAALD:
          description: Is de DDWV crew uitbetaald?
          type: boolean
          example: 1

    oper_diensten:
      type: object
      allOf:
      - $ref: '#/components/schemas/oper_diensten_in' 
      - type: object
        properties:
          ROOSTER_ID: 
            description: Verwijzing naar rooster tabel
            type: integer
            example: 10900  
          INGEVOERD_DOOR_ID: 
            description: Diegene die de dienst heeft ingevoerd. Verwijzing naar leden tabel
            type: integer
            example: 10900  
          VERWIJDERD:
            description: Is dit record gemarkeerd als verwijderd?  
            type: boolean
            example: 0            
          LAATSTE_AANPASSING:
            description: Tijdstempel van laaste aanpassing in de database
            type: string
            format: date-time 
            example: "2020-03-03 17:14:50Z" 

    view_diensten_dataset:
      type: object
      allOf:
        - $ref: '#/components/schemas/oper_diensten'
        - type: object
          properties:
            NAAM: 
              description: Naam van het lid
              type: string
              example: Juffrouw Ooievaar
            INGEVOERD_DOOR: 
              description: Naam van diegene die de dienst heeft ingevoerd
              type: string
              example: Meneer Ooievaar      
            TYPE_DIENST: 
              description: Beschrijving van de dienst
              type: string
              example: Ochtend lierist                

    view_diensten:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 51
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time 
          example: "2016-12-07 09:10:19" 
        hash: 
          description: hash van de dataset
          type: string
          example: "40ab00b"            
        dataset:
          description: De dataset met records
          type: array
          items: 
            $ref: '#/components/schemas/view_diensten_dataset'

    diensten_totaal:
      type: object
      allOf:
      - type: object
        properties:
          LID_ID: 
            description: Verwijzing naar leden tabel
            type: integer
            example: 10900  
          NAAM: 
            description: Naam van het lid
            type: string
            example: Juffrouw Ooievaar            
          JAAR: 
            description: Jaar
            type: integer
            example: 2021  
          MAAND: 
            description: Maand 1..12, null voor jaar totaal
            type: integer
            example: 12       
          AANTAL: 
            description: Aantal diensten
            type: integer
            example: 39               
