openapi: 3.0.2
info:
  title: Login
  description: Inloggen en userinfo
  version: '1.0'
    
paths: 
  /Login/GetUserInfo:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal informatie van de ingelogde gebruiker
      parameters:
        - in: query
          name: DATUM
          description: De datum waarop isStartleider bepaald is. Indien afwezig, dan de dag van vandaag
          required: false
          schema:
            type: string
            format: date  
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Userinfo'
        404:
          description: "Data niet gevonden"    

  /Login/Login:
    get:
      security:
        - basicAuth: []  
      summary: Inloggen
      parameters:
        - in: query
          name: token
          description: token van SMS of Google Authenticator
          required: false
          schema:
            type: string
      responses:
        200:
          description: "OK, ingelogd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        401:
          description: "Mislukt"   
        406:
          description: "Niet aanvaardbaar, input ontbreekt"                      

  /Login/Relogin:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Inloggen
      parameters:
        - in: query
          name: token
          description: bearer token 
          required: false
          schema:
            type: string
      responses:
        200:
          description: "OK, ingelogd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        401:
          description: "Mislukt"   
        406:
          description: "Niet aanvaardbaar, input ontbreekt"   

  /Login/Logout:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Uitloggen en beeindigen van de sessie
      responses:
        200:
          description: "OK, tot de volgende keer"

  //Login/SendSMS:
    get:
      security:
        - basicAuth: [] 
      summary: Verstuur 2 factor security code
      responses:
        200:
          description: "OK, SMS is verstuurd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_leden'
        404:
          description: "Data niet gevonden"
        406:
          description: "Niet aanvaardbaar, input ontbreekt"           
        500:
          description: "Data verwerkingsfout"  

  //Login/ResetWachtwoord:
    get:
      security:
        - basicAuth: []     
      summary: Reset wachtwoord, login naam in basicAuth header
      responses:
        200:
          description: "Aanvraag verwerkt. Ook status 200 als email versturen mislukt is. Dit om te voorkomen dat we te veel info prijsgeven"     
        406:
          description: "Niet aanvaardbaar, input ontbreekt"         
        500:
          description: "Data verwerkingsfout"           

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT         

  schemas:
    token:
      type: object
      properties:
        TOKEN:
          description: JSON Web Token - JWT
          type: string
    ref_leden:
      type: object
      properties:
        ID:
          description: Database ID van het lid record
          type: integer
          format: int32
          example: 12871
        NAAM: 
          description: De volledige naam van het lid
          type: string
          maxLength: 255
          example: Meindert het Paard
        VOORNAAM: 
          description: De voornaam van het lid
          type: string
          maxLength: 15
          example: Meindert        
        TUSSENVOEGSEL: 
          description: De tussenvoegsel van het lid
          type: string
          maxLength: 8
          example: het              
        ACHTERNAAM:
          description: De achternaam van het lid zonder tussenvoegsels
          type: string
          maxLength: 30
          example: Paard        
        ADRES:
          description: Het (post) adres waar het lid woont
          type: string
          maxLength: 50
          example: Werf 18       
        POSTCODE:
          description: De postcode die bij het adres hoort
          type: string
          maxLength: 50
          example: 7158 PP          
        WOONPLAATS:
          description: De plaatsnaam 
          type: string
          maxLength: 50
          example: Berkum                           
        TELEFOON: 
          description: Telefoon nummer van het lid
          type: string
          maxLength: 255
          example: 086-1506822
        MOBIEL: 
          description: Mobiel telefoon nummer van het lid
          type: string
          maxLength: 255
          example: 06-1025500
        NOODNUMMER:
          description: Het telefoonnummer van een naaste, kan gebruikt worden in noodgevallen
          type: string
          maxLength: 255
          example: 0112-11801              
        EMAIL:
          description: email adres van het lid
          type: string
          maxLength: 45
          example: meindert@fabeltje.com
        AVATAR:
          description: url naar avatar
          type: string
          maxLength: 255
          example: https://mijn.vliegclub.org/avatar.gif           
        LIDNR: 
          description: Het lidnummer zoals dat in de leden administratie bekend is
          type: string
          maxLength: 10
          example: 11139        
        LIDTYPE_ID: 
          description: Het soort lid (jeugdlid, lid, donateur). Verwijzing naar type tabel
          type: integer
          format: int32
          example: 603     
        STATUSTYPE_ID: 
          description: De vliegstatus van het lid (DBO, solist, brevethouder), NULL indien niet van toepassing 
          type: integer
          format: int32
          example: 1901      
        ZUSTERCLUB_ID: 
          description: Zusterclub lidmaatschap van lid. Nodig voor DDWV.
          type: integer
          format: int32
          example: 603              
        LIERIST:
          description: Mag dit lid lieren? 
          type: boolean
          example: false
        LIERIST_IO:
          description: Lierist in opleiding
          type: boolean
          example: false
        STARTLEIDER: 
          description: Kan dit lid het startbedrijf leiden?  
          type: boolean
          example: true    
        INSTRUCTEUR:
          description: Heeft dit lid een instructie bevoegdheid?  
          type: boolean
          example: false    
        CIMT:
          description: Heeft dit lid een instructie bevoegdheid?  
          type: boolean
          example: false           
        DDWV_CREW:
          description: Werkt dit lid mee in het DDWV bedrijf  
          type: boolean
          example: false 
        DDWV_BEHEERDER:
          description: Is dit lid de beheerder van het DDWV bedrijf, heeft toegang tot DDWV gerelateede data  
          type: boolean
          example: true 
        BEHEERDER:
          description: Is dit lid de beheerder van deze omgeving, heeft toegang tot alles   
          type: boolean
          example: true 
        STARTTOREN:
          description: Dit account wordt gebruikt om starts in de start toren in te voeren    
          type: boolean
          example: false                            
        ROOSTER:
          description: Is dit lid  belast met het maken van roosters    
          type: boolean
          example: false     
        SLEEPVLIEGER:
          description: Is dit lid ook een sleepvlieger 
          type: boolean
          example: false              
        CLUBBLAD_POST:
          description: Moet clubblad per post verstuurd worden    
          type: boolean
          example: true   
        RAPPORTEUR:
          description: Heeft lid toegang tot alle starts / logboeken voor rapportage    
          type: boolean
          example: true 
        GASTENVLIEGER:
          description: Wordt dit lid ingedeeld om gasten te vliegen   
          type: boolean
          example: true                                                     
        MEDICAL:
          description: Verloopdatum van het medical 
          type: string
          format: date
          example: "2022-01-16"
        TECHNICUS:
          description: Is lid een technicus voor rollend / vliegend. Zo ja dan extra bevoegdheden in Journaal
          type: boolean
          example: true
        GEBOORTE_DATUM:
          description: Geboorte datum van het lid 
          type: string
          format: date
          example: "1932-01-16"          
        INLOGNAAM: 
          description: De inlognaam van het lid
          type: string
          maxLength: 45
          example: mpaard        
        WACHTWOORD: 
          description: Het geheime password, bij ophalen van data altijd "****". Wachtwoord wordt als hash opgeslagen in de database
          type: string
          maxLength: 255
          example: 123456      
        WACHTWOORD_HASH: 
          description: Wachtwoord in Helios hash formaat. Data wordt direct in database opgeslagen zonder encryptie, dat is namelijk al gebeurd. Alleen van toepassing voor SaveObject, komt dus niet terug in GetObject of GetObjects
          type: string
          maxLength: 255
          example: 123456                
        AUTH: 
          description: 2Factor authenticatie voor deze gebruiker  
          type: boolean
          example: true    
        STARTVERBOD: 
          description: Heef het lid een startverbod?  
          type: boolean
          example: false  
        PRIVACY: 
          description: Staat privacy mode (AVG / GDPR) uit/aan 
          type: boolean
          example: true     
        BEPERKINGEN:
          description: Wat zijn de beperkingen (vliegen / diensten) voor dit lid
          type: string
          maxLength: 255
          example: Meindert niet inzetten als startleider, hij gaat gras eten :-)   
        OPMERKINGEN:
          description: Extra text om opmerkingen toe te voegen
          type: string
          maxLength: 255
          example: Voorkeur om 's morgens lierdienst te doen 
    Userinfo:
      type: object
      properties:
        LidData:
          description: Aantal records dat voldoet aan de criteria in de database
          $ref: '#/components/schemas/ref_leden'
        Userinfo:
          type: object
          description: Gebruik dit object voor applicatie permissies
          properties:
            isBeheerderDDWV:
              description: Is de ingelogde gebruiker de DDWV beheerder
              type: boolean
              example: false              
            isBeheerder:
              description: Is de ingelogde gebruiker de applicatie beheerder
              type: boolean
              example: true
            isRooster:
              description: Is de ingelogde gebruiker de rooster maker
              type: boolean
              example: false              
            isInstructeur:
              description: Is de ingelogde gebruiker een instructeur
              type: boolean
              example: false
            isCIMT:
              description: Is de ingelogde gebruiker chef instructeur
              type: boolean
              example: false              
            isStarttoren:
              description: Is de ingelogde gebruiker de starttoren?
              type: boolean
              example: true     
            isRapporteur:
              description: Is de ingelogde gebruiker verantwoordelijk voor start rapportage & logboeken
              type: boolean
              example: true                   
            isDDWVCrew:
              description: Maakt de ingelogde gebruiker onderdeel uit van de DDWV crew ?
              type: boolean
              example: true                 
            isAangemeld:
              description: Is de ingelogde gebruiker aangemeld voor vandaag
              type: boolean
              example: true
            isClubVlieger:
              description: Is de ingelogde gebruiker een lid van de club
              type: boolean
              example: true            
            isDDWV:
              description: Is de ingelogde gebruiker een DDWV vlieger (dus geen club lid)
              type: boolean
              example: false
