openapi: 3.0.2
info:
  title: Transacties
  description: De transacties van DDWV, af en bijschrijvingen
  version: '1.0'
          
paths:
  /Transacties/CreateTable:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat"   

  /Transacties/CreateViews:
    post:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

 
  /Transacties/GetObjects:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: Haal een lijst met records op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 82
        - in: query
          name: EXT_ID
          description: External ID
          required: false
          schema:
            type: integer
            format: int32
            example: 9723156
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: HASH
          description: HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is.
          required: false
          schema:
            type: string                
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query
          name: LID_ID
          description: Haal alle transactie records op van een specifiek lid
          required: false
          schema:
            type: string
        - in: query
          name: VLIEGDAG
          description: Vliegdag, duh....
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: DATUM
          description: Datum van de transactie
          required: false
          schema:
            type: string
            format: date            
        - in: query
          name: BEGIN_DATUM
          description: Begin datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date   
        - in: query
          name: EIND_DATUM
          description: Eind datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date                                                              
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_transactie'
        304:
          description: "Data niet gemodificeerd, HASH in aanroep == hash in dataset"                     
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"          

  /Transacties/GetBanken:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: De banken die iDeal ondersteunen
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/banken'

  /Transacties/StartIDealTransactie:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Start de iDeal transactie
      parameters:
        - in: query
          name: LID_ID
          description: Database ID van het lid die betaalt
          required: true
          schema:
            type: integer
            format: int32        -
        - in: query
          name: BESTEL_ID
          description: Bestelling ID
          required: true
          schema:
            type: integer
            format: int32
            example: 2
        - in: query
          name: BANK_ID
          description: Code van de bank
          required: true
          schema:
            type: string
            example: ABNANL2A
      responses:
        200:
          description: "OK, transactie goed gestart"
          content:
            application/json:
              schema:
                URL:
                  description: URL van ideal
                  type: string
                  example: "https://xyz.com"
  /Tranacties/Validatie:
    - get:
        summary: Verficatie of de betaling gelukt is.
        parameters:
          - in: query
            name: trxid
            description: Het id van de transactie
            required: true
            schema:
              type: integer
              format: int32
          - in: query
            name: idealtrxid
            description: Het ideal id van de transactie
            required: true
            schema:
              type: integer
              format: int32


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT         

  schemas:
    banken:
        type: object
        properties:
          ID:
            description: ID van de bank
            type: string
            example: "ABNANL2A"
          NAAM:
            description: Naam van de bank
            type: string
            example: "ABN AMRO"

    oper_transactie_in:
      type: object
      properties:
        ID:
          description: Database ID van het record
          type: integer
          format: int32
          example: 14
        DATUM:
          description: Datum van de transacties 
          type: string
          format: date
          example: "2022-03-29"
        VLIEGDAG:
          description: Datum van de vliegdag
          type: string
          format: date
          example: "2022-04-02"
        LID_ID:
          description: Voor welk is de transactie
          type: integer
          format: int32
          example: 10115
        INGEVOERD_ID:
          description: Door wie is deze transactie aangemaakt
          type: integer
          format: int32
          example: 10115
        TYPE_ID:
          description: Type voor transactie, verwijzing naar type tabel
          type: integer
          format: int32
          example: 2004
        BETAALD:
            description: Een bijschrijving van eenheden (betaald via bank)
            type: boolean
            example: 0            
        DDWV:
            description: De afschrijving komt door een DDWV dag
            type: boolean
            example: 0   
        BEDRAG:
            description: Het bedrag in Euro's
            type: number
            format: double
            example: 0          
        EENHEDEN:
            description: Aantal strips voor deze transactie
            type: integer
            format: numeric
            example: 10115        
        SALDO_VOOR:
            description: Het aantal eenheden voordat de transactie gestart is
            type: number
            format: double
            example: 0      
        SALDO_NA:
            description: Het aantal eenheden nadat de transactie afgerond is
            type: number
            format: double
            example: 0   
        REFERENTIE:
          description: Een referentie naar vliegdag
          type: string
          example: "vliegdag 2022-04-01"
        EXT_REF:
          description: Een externe referentie van de ideal transactie
          type: string
          example: "0112 8854 9854488"
        OMSCHRIJVING:
          description: Omschrijving van handmatige correctie
          type: string
          example: "Ivm defecte lier, strippen retour"
        BETAALD_URL:
          description: Verwijzing naar extern url van de bank 
          type: string
          example: https://pay.digiwallet.nl/test-transaction?transactionID=190210863&paymethod=IDE&hash=9c416bdd18cb1"

    oper_transactie:
      type: object
      allOf:
      - $ref: '#/components/schemas/oper_transactie_in' 
      - type: object
        properties:   
          VERWIJDERD:
            description: Is dit record gemarkeerd als verwijderd?  
            type: boolean
            example: 0        
          LAATSTE_AANPASSING:
            description: Tijdstempel van laaste aanpassing in de database
            type: string
            format: date-time 
            example: "2021-05-05 20:13:59Z" 

    view_transactie_dataset:
      type: object
      allOf:
        - $ref: '#/components/schemas/oper_transactie'
        - type: object
          properties:
            NAAM:
              description: De naam van het lid voor deze transactie
              type: string
              example: Momfer de Mol       
            INGEVOERD:
              description: De naam van het lid voor deze transactie
              type: string
              example: Momfer de Mol
            TYPE:
              description: Omschrijving van het type transactie
              type: string
              example: Cancelen vliegdag

    view_transactie:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time 
          example: "2019-01-05 10:09:53" 
        hash: 
          description: hash van de dataset
          type: string
          example: "9302aa0"            
        dataset:
          description: De dataset met records
          type: array
          items: 
            $ref: '#/components/schemas/view_transactie_dataset'                     
