openapi: 3.0.2
info:
  title: Aanwezige Vliegtuigen
  description: Welke vliegtuigen zijn op een vliegdag aanwezig op het veld. Dan kunnen we sneller een keuze maken
  version: '1.0'
            
paths:
  /AanwezigVliegtuigen/CreateTable:
    post:
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat" 

  /AanwezigVliegtuigen/CreateViews:
    post:
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /AanwezigVliegtuigen/GetObject:
    get:
      summary: Haal een enkel record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 5
        - in: query
          name: VLIEGTUIG_ID
          description: Vliegtuig ID (ID uit ref_vliegtuigen). Werkt alleen als ID null is. Bovendien is DATUM vereist
          required: false
          schema:
            type: integer
            format: int32
            example: 10855
        - in: query
          name: DATUM
          description: DATUM van de vliegdag. Werkt alleen als ID null is. Bovendien is LID_ID vereist
          required: false
          schema:
            type: string
            format: date
            example: "1999-01-01"                     
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_vliegtuigen'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"           
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"       

  /AanwezigVliegtuigen/GetObjects:
    get:
      summary: Haal de aanwezigheidslijst op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 23 
        - in: query
          name: VERWIJDERD
          description: Toon welke records verwijderd zijn. Default = false
          required: false
          schema:
            type: boolean                 
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = NAAM
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query        
          name: SELECTIE
          description: Zoek in de NAAM van de aanwezige
          required: false
          schema:
            type: string    
        - in: query        
          name: IN
          description: Een of meerdere vliegtuigen database IDs in CSV formaat
          required: false
          schema:
            type: string                
        - in: query
          name: BEGIN_DATUM
          description: Begin datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date   
        - in: query
          name: EIND_DATUM
          description: Eind datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date                                              
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_aanwezig_vliegtuigen'
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"    

  /AanwezigVliegtuigen/Aanmelden:
    post:
      summary: Aanmelden van het lid als aanwezig. Maakt record aan als het niet bestaat of update bestaand record (ook al is het lid aanwezig)
      requestBody:
        description: Lid data
        required: true
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/oper_aanwezig_vliegtuigen_in' 
              - type: object
                properties:
                  TIJDSTIP:
                    description: Tijdstip van de aanmelding. Indien afwezig, huidige tijd. ISO8601
                    type: string
                    format: date-time 
                    example: "2018-03-22T10:32:28Z"        
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_vliegtuigen' 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigVliegtuigen/Afmelden:
    post:
      summary: Afmelden van het vliegtuig als aanwezig. Update bestaand record. Vliegtuig moet aanwezig zijn
      requestBody:
        description: Lid data
        required: true
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/oper_aanwezig_vliegtuigen_in' 
              - type: object
                properties:      
                  TIJDSTIP:
                    description: Tijdstip van de afmelding. Indien afwezig, huidige tijd. ISO8601
                    type: string
                    format: date-time 
                    example: "2017-07-21T09:32:28Z"
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_vliegtuigen' 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Lid is niet aanwezig"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigVliegtuigen/DeleteObject:
    delete:
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record. Meerdere ID's in CSV formaat
          required: false
          schema:
            type: string
        - in: query
          name: DATUM
          description: Datum van de vliegdag 
          schema:
            type: string
            format: date
            example: "2017-07-21" 
        - in: query              
          name: VLIEGTUIG_ID
          description: Het vliegtuig ID. Verwijzing naar vliegtuigen tabel
          schema:
            type: integer
            example: 200    
        - in: query
          name: VERIFICATIE
          description: Controleer of record bestaat voordat het verwijderd wordt. Default = true
          required: false
          schema:
            type: boolean            
      responses:
        204:
          description: "Aanwezig record verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigVliegtuigen/RestoreObject:
    patch:
      summary: Record dat verwijderd is terug halen. VERWIJDERD marker kijrgt reset
      parameters:
        - in: query
          name: ID
          description: Database ID van het record. Meerdere ID's in CSV formaat
          required: true
          schema:
            type: string           
      responses:
        202:
          description: "Record(s) hersteld" 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigVliegtuigen/SaveObject:
    post:
      summary: Voeg nieuwe aanmelding toe
      requestBody:
        description: Aanmelding data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_aanwezig_vliegtuigen_in'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_vliegtuigen'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, lid is al aanwezig"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                      
    put:
      summary: Update bestaande aanmelding. DATUM / LID_ID kunnen niet aangepast worden. Indien deze velden onjuist onjuist zijn, verwijder record en maak nieuw record.
      requestBody:
        description: Aanmelding data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_aanwezig_vliegtuigen_in'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_vliegtuigen'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"                
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, lid is al/niet aanwezig op deze dag" 
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"  

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is

  schemas:
    oper_aanwezig_vliegtuigen_in:
      type: object
      properties:
        ID:
          description: Database ID van het aanwezig record
          type: integer
          format: int32
          example: 12871
        DATUM:
          description: Datum van de vliegdag 
          type: string
          format: date
          example: "2017-07-21"
        VLIEGTUIG_ID: 
          description: Het vliegtuig ID. Verwijzing naar vliegtuigen tabel
          type: integer
          example: 215       
        AANKOMST: 
          description: Aankomsttijd van het vliegtuig. ISO8601
          type: string
          pattern: '^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$'
          example: "09:32:28"
        VERTREK: 
          description: Vertrektijd van het vliegtuig. ISO8601
          type: string
          pattern: '^([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$'
          example: "17:32:28"
        LATITUDE: 
          description: Positie van het vliegtuig in latitude
          type: number
          format: double
          minimum: -90
          maximum: 90
          example: 52.11231
        LONGITUDE: 
          description: Positie van het vliegtuig in longitude
          type: number
          format: double
          minimum: -180
          maximum: 180
          example: 4.61754           
        HOOGTE: 
          description: Hoogte van het vliegtuig in meters
          type: number
          format: int
          example: 694
        SNELHEID: 
          description: Snelheid van het vliegtuig in km/h
          type: number
          format: int
          example: 95         

    oper_aanwezig_vliegtuigen:
      type: object
      allOf:
      - $ref: '#/components/schemas/oper_aanwezig_vliegtuigen_in' 
      - type: object
        properties:
          VERWIJDERD:
            description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
            type: boolean
            example: 0            
          LAATSTE_AANPASSING:
            description: Tijdstempel van laaste aanpassing in de database
            type: string
            format: date-time 
            example: "2020-09-18 09:51:16" 

    view_aanwezig_vliegtuigen:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time 
          example: "2013-04-20 08:01:00"
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/oper_aanwezig_vliegtuigen'
              - type: object
                properties:                   
                  REG_CALL: 
                    description: Vliegtuig registratie en callsign van het vliegtuig
                    type: string
                    example: PH-1076 (E2)  