openapi: 3.0.2
info:
  title: DDWV
  description: DDWV
  version: '1.0'
       
paths: 
  /DDWV/GetConfiguratie:
    get:
      security:
        - basicAuth: [] 
        - bearerAuth: []     
      summary: De DDWV configuratie

      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ddwv_config'

  /DDWV/ToetsingDDWV:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Annuleren van de vliegdag en terug boeken naar leden
      parameters:
        - in: query
          name: DATUM
          description: Datum van de te annuleren vliegdag
          schema:
            type: string
            format: date
          example: "2024-04-12"
        - in: query
          name: HASH
          description: sha1 encoding van het rooster record (als json)
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_leden'
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Parameters ontbreken"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /DDWV/UitbetalenCrew:
    post:
      security:
        - basicAuth: []
        - bearerAuth: []
      summary: Betalen van de crew na bewezen diensten
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uitbetalen'
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_leden'
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"
        406:
          description: "Parameters ontbreken"
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT         

  schemas:
    ddwv_config:
      type: object
      properties:
        DDWV: 
          description: Is DDWV software actief
          type: boolean
        START: 
          description: Eerte DDWV dag van het seizoen
          type: string
        EIND: 
          type: string
        MAX_STRIPPEN: 
          type: integer
          format: int32
        STRIPPEN_RETOUR_OP_VLIEGDAG: 
          type: integer
          format: int32
        TARIEVEN: 
          description: De dataset met records
          additionalProperties:
            $ref: '#/components/schemas/ddwv_tarieven'

    ddwv_tarieven:
      type: object
      properties:
        TIJDSTIP: 
          description: Moment van boeken DDWV dag
          type: string
          example: 3  
        EENHEDEN: 
          description: Aantal strippen die afgeschreven worden
          type: integer
          example: 8

    uitbetalen:
      type: object
      properties:
        DATUM:
          description: Datum van de uitbetaling
          type: string
          format: date
          example: "2017-07-21"
        DIENSTEN:
          description: Diensten IDs in CSV formaat
          type: string
          example: 1375,1380,1398
