openapi: 3.0.2
info:
  title: Progressie kaart
  description: Welke competenties heeft dit lid zich eigen gemaakt
  version: '1.0'
        
paths:
  /Progressie/CreateTable:
    post:
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat"   

  /Progressie/CreateViews:
    post:
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /Progressie/GetObject:
    get:
      summary: Haal een enkel record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het type record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_progressie'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"    
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"     

  /Progressie/GetObjects:
    get:
      summary: Haal een lijst met competeties op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 27      
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query
          name: LEERFASE_ID
          description: Haal alle types op van een specieke leerfase
          required: false
          schema:
            type: string                           
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_progressie'
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"          

  /Progressie/DeleteObject:
    delete:
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        204:
          description: "Type verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten" 
        404:
          description: "Data niet gevonden"             
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Progressie/SaveObject:
    post:
      summary: Voeg nieuw type record toe
      requestBody:
        description: type data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_progressie'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_progressie'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                          
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"   
        409:
          description: "Conflict, record bestaat al"                     
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                       
    put:
      summary: Update bestaand type record
      requestBody:
        description: type data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_progressie'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_progressie'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten" 
        404:
          description: "Data niet gevonden"                          
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"             
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"  

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is

  schemas:
    ref_progressie:
      type: object
      properties:
        ID:
          description: Database ID van het record
          type: integer
          format: int32
          example: 92113
        LID_ID:
          description: Lid ID (ID uit ref_leden)
          type: integer
          format: int32
          example: 1    
        COMPETENTIE_ID:
          description: Welke comptententie heeft dit lid zich eigen gemaakt. Verwijzing naar ref_competenties
          type: integer
          format: int32
          example: 54
        INSTRUCTEUR_ID:
          description: Door wie is de competentie toegevoegd voor de lid
          type: integer
          format: int32
          example: 10001             
        OPMERKINGEN:
          description: Opmerking over de behaalde competentie
          type: string
          example: "Heeft aangetoond dat de vaardigheden volledig beheerst"
        INGEVOERD:
          description: Tijdstempel wanneer record is toegevoegd
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18            
        LINK_ID:
          description: Verwijzing naar eerder ingevoerde data
          type: integer
          format: int32
          example: 1655          
        VERWIJDERD:
          description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
          type: boolean
          example: 0        
        LAATSTE_AANPASSING:
          description: Tijdstempel van laaste aanpassing in de database
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
    view_progressie:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/ref_progressie'
              - type: object
                properties:                   
                  LEERFASE: 
                    description: Fase van de vliegopleiding
                    type: string
                    example: Voortgezette vliegopleiding 1    
                  COMPETENTIE: 
                    description: Volledige omschrijving van de compententie
                    type: string
                    example: Uitstap procedure
                  LID_NAAM:
                    description: De volledige naam van het lid
                    type: string
                    example: Meindert het Paard 
                  INSTRUCTEUR_NAAM:
                    description: De volledige naam van de instrcuteur die de competentie heeft toegevoegd
                    type: string
                    example: "Lowieke de Vos"  
# kopie van competenties                     
    ref_competenties:
      type: object
      properties:
        ID:
          description: Database ID van het record
          type: integer
          format: int32
          example: 12871
        VOLGORDE:
          description: Volgorde van weergave
          type: integer
          format: int16
          example: 1          
        LEERFASE_ID:
          description: In welke leerfase zit deze competentie. Verwijzing naar ref_types
          type: integer
          format: int32
          example: 1
        BLOK:
          description: Volgnummer
          type: string
          maxLength: 7
          example: "3.4"
        ONDERWERP:
          description: Volledige omschrijving van de compententie
          type: string
          maxLength: 75
          example: Uitstap procedure
        DOCUMENTATIE:
          description: Verwijzing naar de volledige documentie
          type: string
          maxLength: 75
          example: "VVO1.14"
        VERWIJDERD:
          description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
          type: boolean
          example: 0        
        LAATSTE_AANPASSING:
          description: Tijdstempel van laaste aanpassing in de database
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
    view_competenties:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/ref_compententies'
              - type: object
                properties:                   
                  LEERFASE: 
                    description: Fase van de vliegopleiding
                    type: string
                    example: Voortgezette vliegopleiding 1                                              
#einde kopie
    competenties_kaart:
      type: object
      properties:
        totaal:
          description: Aantal records van de comptentie kaart
          type: integer
          format: int32
          example: 103
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database op de progressei tabel
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/ref_compententies'
              - type: object
                properties:                   
                  LEERFASE: 
                    description: Fase van de vliegopleiding
                    type: string
                    example: Voortgezette vliegopleiding 1          